server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    include /etc/nginx/includes/security-headers.conf;
    include /etc/nginx/includes/app-locations.conf;
}
